development:
  adapter: redshift
  host: localhost
  port: 5439
  database: olapl2
  username: admin
  password: Innocycle123
  encoding: utf8
  pool: 3
  timeout: 5000

staging:
  adapter: redshift
  host: platform-reboot
  port: 5439
  database: olapl2_test
  username: admin
  password: Innocycle123
  encoding: utf8
  pool: 3
  timeout: 5000

production:
  adapter: redshift
  host: platform-reboot
  port: 5439
  database: olapl2_test
  username: admin
  password: Innocycle123
  encoding: utf8
  pool: 3
  timeout: 5000
